# Generated by Django 5.1.2 on 2024-11-10 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enclos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("superficie", models.FloatField(help_text="Superficie en m²")),
            ],
        ),
        migrations.CreateModel(
            name="Soigneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "experience",
                    models.IntegerField(help_text="Nombre d'années d'expérience"),
                ),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("description", models.CharField(max_length=1000)),
                (
                    "enclos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zoo.enclos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("date_naissance", models.DateField()),
                ("date_arrivee", models.DateField(blank=True, null=True)),
                (
                    "enclos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zoo.enclos"
                    ),
                ),
                (
                    "soigneur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zoo.soigneur",
                    ),
                ),
            ],
        ),
    ]
