# Generated by Django 5.1.2 on 2024-11-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="templates/images/"
            ),
        ),
    ]
