# Generated by Django 5.1.2 on 2024-11-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoo", "0003_alter_animal_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="enclos",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
